### ISSUE TITLE
Open ideas of enhancements - todo list

### ISSUE THREAD

**Issue by RARgames** [RARgames/planka#1]
- [x] Ctrl+Enter when creating a task opens edit menu
- [x] Sum cards in column, in board
- [x] Colapse column to save screen space
- [x] Always visible scroll bar
- [x] Add sidebar for choosing projects/boards with toggle ON/OFF in settings
- [x] Better dashboard with project/boards stats
- [x] User groups: user group can be added to the project or the board (instead of to the whole system), Individual users, user groups can be added to the project/board. Probably a structure [Organization -> Team -> User] is a better option and could help in the future.
- [x] Full dark mode: alternative colors for task etc.
- [x] Filter task by name (the same field should allow #Label, @Member, task_number filtering)
- [x] Add task numbering in each board (so each task has its id: 1, 2, 3, and you can see a small # 1, # 2 somewhere near the task name. It can speed up finding tasks, also added to filter by) In a synchronized board it, clicking task number should open github issue. (Open questions: how to handle issues+PRs? Discuss details)
- [x] Add github-like task close option (like issues) Default action should be close, which can move the task to a new hidden by default column: archived. Delete is possible by using other button - more destructive action, as you cannot get the task back.
- [x] Github issues synchronized board - on setup get all issues from github and copy to the internal database, then 2-way sync (Columns can be saved using labels with prefixes, not displayed in Planka, if needed) Each user needs its GIthub authorization to use the board, without that the synchronized board is read-only. (Discuss details)
- [x] Parse #Label @Member when creating a task and automatically add labels and members on creation
- [x] Convert - [ ] from description to a working task list
- [x] Alternative layout/change the current layout of editing a task: Edit menu opens on the right of the screen, you can still scroll through other issues, select them, move, etc. with toggle ON/OFF in settings
- [x] Move tasks to a different column when hovering over +Add another card with a task, right now it cancels action
- [x] Add option to show image only in the description by default
- [x] Images and labesl below the title
- [x] Add column names to cards at the top
- [x] Better edit menus (pencil button) - more compact menus without extra texts
- [x] Right click to open context menus
- [x] Add extra language pack for advanced users - e.g. enterCardTitle: 'Enter card title... [Ctrl+Enter] to open'
- [x] AddCard should not close when there is something inside
- [x] Enhance pages e.g. login page - center login form
- [x] Github-like confirm deleting whole board to further prevent accidential deletion
- [x] Final check if every used old workflow is available
- [x] Bug: Multiline list titles break board view
- [x] Bug: Cards added to list appear at wrong order when filtering is on + card sorting when filtering is on

Sidebar should be available as an alternate layout. In sidebar there are projects. Each project has its own dashboard and boards in a list.

In the project dashboard each board has its own box with the following info:
- name of the board
- members
- board actions
- scrollable stats: columns and number of cards
- activity graph for last 30 days?

and additional box where you can create new board
